printWidth: 80
bracketSpacing: true
jsxBracketSameLine: true
semi: true
singleQuote: true
useTabs: true
tabWidth: 2
trailingComma: all
proseWrap: always

overrides:
  - files: ['**/package.json']
    options:
      printWidth: 999
      tabWidth: 2
      useTabs: false
  - files: ['**/README.md']
    options:
      tabWidth: 2
      useTabs: false
